# This file was *autogenerated* from the file argyrisFunctions.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_18p5 = RealNumber('18.5'); _sage_const_1p25 = RealNumber('1.25'); _sage_const_8 = Integer(8); _sage_const_0p25 = RealNumber('0.25'); _sage_const_13p5 = RealNumber('13.5'); _sage_const_32 = Integer(32); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_3p5 = RealNumber('3.5'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_0p75 = RealNumber('0.75'); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_30 = Integer(30); _sage_const_18 = Integer(18)#------------------------------------------------------------------------------
# argyrisFunctions.sage
# Author: David Wells <drwells@vt.edu>
# Description: Sage (Python) file containing a list of Argyris functions. Some
# manual labor is needed to create the modules of derivatives for Haskell.
#------------------------------------------------------------------------------
var('x,y')

listOfLists = [[_sage_const_1  - _sage_const_10 *x**_sage_const_3  - _sage_const_10 *y**_sage_const_3  + _sage_const_15 *x**_sage_const_4  - _sage_const_30 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_15 *y**_sage_const_4  - _sage_const_6 *x**_sage_const_5  + _sage_const_30 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_30 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_6 *y**_sage_const_5 ],
[_sage_const_10 *x**_sage_const_3  - _sage_const_15 *x**_sage_const_4  + _sage_const_15 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_6 *x**_sage_const_5  - _sage_const_15 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_15 *x**_sage_const_2 *y**_sage_const_3 ],
[_sage_const_10 *y**_sage_const_3  + _sage_const_15 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_15 *y**_sage_const_4  - _sage_const_15 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_15 *x**_sage_const_2 *y**_sage_const_3  + _sage_const_6 *y**_sage_const_5 ],
[x - _sage_const_6 *x**_sage_const_3  - _sage_const_11 *x*y**_sage_const_2  + _sage_const_8 *x**_sage_const_4  + _sage_const_10 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_18 *x*y**_sage_const_3  - _sage_const_3 *x**_sage_const_5  + x**_sage_const_3 *y**_sage_const_2  - _sage_const_10 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_8 *x*y**_sage_const_4 ],
[y - _sage_const_11 *x**_sage_const_2 *y - _sage_const_6 *y**_sage_const_3  + _sage_const_18 *x**_sage_const_3 *y + _sage_const_10 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_8 *y**_sage_const_4  - _sage_const_8 *x**_sage_const_4 *y - _sage_const_10 *x**_sage_const_3 *y**_sage_const_2  + x**_sage_const_2 *y**_sage_const_3  - _sage_const_3 *y**_sage_const_5 ],
[-_sage_const_4 *x**_sage_const_3  + _sage_const_7 *x**_sage_const_4  - _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_3 *x**_sage_const_5  + _sage_const_3p5 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_3 ],
[-_sage_const_5 *x**_sage_const_2 *y + _sage_const_14 *x**_sage_const_3 *y + _sage_const_18p5 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_8 *x**_sage_const_4 *y - _sage_const_18p5 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_13p5 *x**_sage_const_2 *y**_sage_const_3 ],
[-_sage_const_5 *x*y**_sage_const_2  + _sage_const_18p5 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_14 *x*y**_sage_const_3  - _sage_const_13p5 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_18p5 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_8 *x*y**_sage_const_4 ],
[-_sage_const_4 *y**_sage_const_3  - _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_7 *y**_sage_const_4  + _sage_const_3p5 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_3 *y**_sage_const_5 ],
[_sage_const_0p5 *x**_sage_const_2  - _sage_const_1p5 *x**_sage_const_3  + _sage_const_1p5 *x**_sage_const_4  - _sage_const_1p5 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_0p5 *x**_sage_const_5  + _sage_const_1p5 *x**_sage_const_3 *y**_sage_const_2  + x**_sage_const_2 *y**_sage_const_3 ],
[x*y - _sage_const_4 *x**_sage_const_2 *y - _sage_const_4 *x*y**_sage_const_2  + _sage_const_5 *x**_sage_const_3 *y + _sage_const_10 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_5 *x*y**_sage_const_3  - _sage_const_2 *x**_sage_const_4 *y - _sage_const_6 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_6 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_2 *x*y**_sage_const_4 ],
[_sage_const_0p5 *y**_sage_const_2  - _sage_const_1p5 *y**_sage_const_3  - _sage_const_1p5 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_1p5 *y**_sage_const_4  + x**_sage_const_3 *y**_sage_const_2  + _sage_const_1p5 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_0p5 *y**_sage_const_5 ],
[_sage_const_0p5 *x**_sage_const_3  - x**_sage_const_4  + _sage_const_0p25 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_0p5 *x**_sage_const_5  - _sage_const_0p25 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_0p25 *x**_sage_const_2 *y**_sage_const_3 ],
[x**_sage_const_2 *y - _sage_const_3 *x**_sage_const_3 *y - _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_2 *x**_sage_const_4 *y + _sage_const_3p5 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_2p5 *x**_sage_const_2 *y**_sage_const_3 ],
[_sage_const_1p25 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_0p75 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_1p25 *x**_sage_const_2 *y**_sage_const_3 ],
[_sage_const_1p25 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_1p25 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_0p75 *x**_sage_const_2 *y**_sage_const_3 ],
[x*y**_sage_const_2  - _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_3 *x*y**_sage_const_3  + _sage_const_2p5 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_3p5 *x**_sage_const_2 *y**_sage_const_3  + _sage_const_2 *x*y**_sage_const_4 ],
[_sage_const_0p5 *y**_sage_const_3  + _sage_const_0p25 *x**_sage_const_2 *y**_sage_const_2  - y**_sage_const_4  - _sage_const_0p25 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_0p25 *x**_sage_const_2 *y**_sage_const_3  + _sage_const_0p5 *y**_sage_const_5 ],
[(sqrt(_sage_const_2 )) * (-_sage_const_8 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_8 *x**_sage_const_3 *y**_sage_const_2  + _sage_const_8 *x**_sage_const_2 *y**_sage_const_3 )],
[-_sage_const_16 *x*y**_sage_const_2  + _sage_const_32 *x**_sage_const_2 *y**_sage_const_2  + _sage_const_32 *x*y**_sage_const_3  - _sage_const_16 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_32 *x**_sage_const_2 *y**_sage_const_3  - _sage_const_16 *x*y**_sage_const_4 ],
[-_sage_const_16 *x**_sage_const_2 *y + _sage_const_32 *x**_sage_const_3 *y + _sage_const_32 *x**_sage_const_2 *y**_sage_const_2  - _sage_const_16 *x**_sage_const_4 *y - _sage_const_32 *x**_sage_const_3 *y**_sage_const_2  - _sage_const_16 *x**_sage_const_2 *y**_sage_const_3 ]]

# create the first derivatives.
firstDerivativesOfX = map((lambda equation : [diff(equation[_sage_const_0 ],x)]), listOfLists)
firstDerivativesOfY = map((lambda equation : [diff(equation[_sage_const_0 ],y)]), listOfLists)

print "first derivatives of x:"
print firstDerivativesOfX

print "first derivatives of y:"
print firstDerivativesOfY

# and the second derivatives
secondDerivativesOfX = map((lambda equation : [diff(equation[_sage_const_0 ],x,_sage_const_2 )]), listOfLists)
secondDerivativesOfY = map((lambda equation : [diff(equation[_sage_const_0 ],y,_sage_const_2 )]), listOfLists)

print "second derivatives of x:"
print secondDerivativesOfX

print "second derivatives of y:"
print secondDerivativesOfY

# and the mixed second derivatives
secondDerivativesMixed = map((lambda equation : [diff(diff(equation[_sage_const_0 ],x),y)]), listOfLists)

print "second derivatives, mixed:"
print secondDerivativesMixed
